import { writeFile } from 'node:fs/promises';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Round } from '@movie-quotes/shared';
import { DATA_DIR, FIXTURES_DIR } from '../config.js';
import type { GenreRecord, MovieRecord, QuoteRecord } from '../types.js';
import type { Neighbor } from './neighbors.js';
import { insertRows, type SqlValue } from '../util/sql.js';
import { readJson } from '../util/fs.js';
import { log } from '../util/log.js';

function moviesSql(movies: MovieRecord[]): string {
  const rows: SqlValue[][] = movies.map((m) => [
    m.id,
    m.title,
    m.year,
    m.decade,
    m.tmdbRating,
    m.tmdbVotes,
    m.posterPath,
  ]);
  return insertRows(
    'movies',
    ['id', 'title', 'year', 'decade', 'tmdb_rating', 'tmdb_votes', 'poster_path'],
    rows,
  );
}

function genresSql(genres: GenreRecord[]): string {
  return insertRows(
    'genres',
    ['id', 'name'],
    genres.map((g) => [g.id, g.name]),
  );
}

function movieGenresSql(movies: MovieRecord[]): string {
  const rows: SqlValue[][] = [];
  for (const m of movies) {
    for (const genreId of m.genreIds) rows.push([m.id, genreId]);
  }
  return insertRows('movie_genres', ['movie_id', 'genre_id'], rows);
}

function quotesSql(quotes: QuoteRecord[]): string {
  return insertRows(
    'quotes',
    ['id', 'movie_id', 'text', 'character'],
    quotes.map((q) => [q.id, q.movieId, q.text, q.character]),
  );
}

function neighborsSql(map: Record<string, Neighbor[]>): string {
  const rows: SqlValue[][] = [];
  for (const [quoteId, list] of Object.entries(map)) {
    for (const n of list) rows.push([Number(quoteId), n.neighborId, n.score]);
  }
  return insertRows('quote_neighbors', ['quote_id', 'neighbor_id', 'score'], rows);
}

function roundsSql(pool: Round[]): string {
  return insertRows(
    'rounds',
    [
      'id',
      'answer_quote_id',
      'movie_id',
      'decade',
      'primary_genre_id',
      'band',
      'avg_similarity',
      'decoy_pool',
    ],
    pool.map((r) => [
      r.id,
      r.answerQuoteId,
      r.movieId,
      r.decade,
      r.primaryGenreId,
      r.band,
      r.avgSimilarity,
      JSON.stringify(r.decoyPool),
    ]),
  );
}

export async function load(): Promise<void> {
  log.step('load: generate D1 seed SQL');
  const movies = await readJson<MovieRecord[]>(resolve(DATA_DIR, 'movies.json'));
  const genres = await readJson<GenreRecord[]>(resolve(DATA_DIR, 'genres.json'));
  const quotes = await readJson<QuoteRecord[]>(resolve(DATA_DIR, 'quotes.json'));
  const neighborMap = await readJson<Record<string, Neighbor[]>>(
    resolve(DATA_DIR, 'neighbors.json'),
  );
  const pool = await readJson<Round[]>(resolve(DATA_DIR, 'rounds.json'));

  // Only movies that actually produced rounds are worth seeding.
  const usedMovieIds = new Set(pool.map((r) => r.movieId));
  const usedMovies = movies.filter((m) => usedMovieIds.has(m.id));

  const header = '-- Generated by the pipeline load stage. Do not edit by hand.\n\n';

  const full =
    header +
    genresSql(genres) +
    moviesSql(usedMovies) +
    movieGenresSql(usedMovies) +
    quotesSql(quotes) +
    neighborsSql(neighborMap) +
    roundsSql(pool);
  await writeFile(resolve(DATA_DIR, 'seed.sql'), full, 'utf8');

  // Lean fixture for local dev, CI, and e2e: everything the API needs at runtime
  // (rounds are pre-generated, so quote_neighbors is not required to play).
  const fixture =
    header +
    genresSql(genres) +
    moviesSql(usedMovies) +
    movieGenresSql(usedMovies) +
    quotesSql(quotes) +
    roundsSql(pool);
  await mkdir(FIXTURES_DIR, { recursive: true });
  await writeFile(resolve(FIXTURES_DIR, 'seed.sql'), fixture, 'utf8');

  log.info(
    `load complete: ${usedMovies.length} movies, ${quotes.length} quotes, ${pool.length} rounds`,
  );
  log.info('apply locally: from apps/api run "pnpm db:reset" then "pnpm db:seed"');
}

load().catch((error) => {
  log.warn(String(error));
  process.exit(1);
});
