import { writeFile } from 'node:fs/promises';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
import type { Round } from '@movie-quotes/shared';
import { DATA_DIR, FIXTURES_DIR } from '../config.js';
import type { GenreRecord, MovieRecord, QuoteRecord } from '../types.js';
import { insertRows, type SqlValue } from '../util/sql.js';
import { readJson } from '../util/fs.js';
import { log } from '../util/log.js';

/** Number of films to include in the small committed test fixture. */
const FIXTURE_MOVIES = 24;

function moviesSql(movies: MovieRecord[]): string {
  const rows: SqlValue[][] = movies.map((m) => [
    m.id,
    m.title,
    m.year,
    m.decade,
    m.tmdbRating,
    m.tmdbVotes,
    m.posterPath,
  ]);
  return insertRows(
    'movies',
    ['id', 'title', 'year', 'decade', 'tmdb_rating', 'tmdb_votes', 'poster_path'],
    rows,
  );
}

function genresSql(genres: GenreRecord[]): string {
  return insertRows(
    'genres',
    ['id', 'name'],
    genres.map((g) => [g.id, g.name]),
  );
}

function movieGenresSql(movies: MovieRecord[]): string {
  const rows: SqlValue[][] = [];
  for (const m of movies) {
    for (const genreId of m.genreIds) rows.push([m.id, genreId]);
  }
  return insertRows('movie_genres', ['movie_id', 'genre_id'], rows);
}

function quotesSql(quotes: QuoteRecord[]): string {
  return insertRows(
    'quotes',
    ['id', 'movie_id', 'text', 'character'],
    quotes.map((q) => [q.id, q.movieId, q.text, q.character]),
  );
}

function roundsSql(pool: Round[]): string {
  return insertRows(
    'rounds',
    [
      'id',
      'answer_quote_id',
      'movie_id',
      'decade',
      'primary_genre_id',
      'band',
      'avg_similarity',
      'rand',
      'decoy_pool',
    ],
    pool.map((r) => [
      r.id,
      r.answerQuoteId,
      r.movieId,
      r.decade,
      r.primaryGenreId,
      r.band,
      r.avgSimilarity,
      r.rand,
      JSON.stringify(r.decoyPool),
    ]),
  );
}

export async function load(): Promise<void> {
  log.step('load: generate D1 seed SQL');
  const movies = await readJson<MovieRecord[]>(resolve(DATA_DIR, 'movies.json'));
  const genres = await readJson<GenreRecord[]>(resolve(DATA_DIR, 'genres.json'));
  const quotes = await readJson<QuoteRecord[]>(resolve(DATA_DIR, 'quotes.json'));
  const pool = await readJson<Round[]>(resolve(DATA_DIR, 'rounds.json'));

  const header = '-- Generated by the pipeline load stage. Do not edit by hand.\n\n';

  // Seed every movie and quote so decoy_pool references never dangle. Neighbors
  // are a build-only artifact (rounds carry their decoys), so they are not seeded.
  const full =
    header +
    genresSql(genres) +
    moviesSql(movies) +
    movieGenresSql(movies) +
    quotesSql(quotes) +
    roundsSql(pool);
  await writeFile(resolve(DATA_DIR, 'seed.sql'), full, 'utf8');

  // Movies that actually produced rounds, used to seed the small test fixture.
  const usedMovieIds = new Set(pool.map((r) => r.movieId));
  const usedMovies = movies.filter((m) => usedMovieIds.has(m.id));

  // The committed test fixture is a small, self-contained subset for local dev,
  // CI, and e2e. Only (re)write it when explicitly asked, so a full-corpus run
  // does not bloat the repo. The full data/seed.sql above is what seeds prod.
  if (process.env.WRITE_FIXTURE) {
    const fixtureMovies = usedMovies.slice(0, FIXTURE_MOVIES);
    const fixtureMovieIds = new Set(fixtureMovies.map((m) => m.id));
    const fixtureQuotes = quotes.filter((q) => fixtureMovieIds.has(q.movieId));
    const fixtureQuoteIds = new Set(fixtureQuotes.map((q) => q.id));
    // Keep only rounds that are fully playable within the subset. Trim each
    // decoy pool to in-subset quotes so the API's top-of-pool picks always exist.
    const fixtureRounds = pool
      .filter((r) => fixtureMovieIds.has(r.movieId) && fixtureQuoteIds.has(r.answerQuoteId))
      .map((r) => ({ ...r, decoyPool: r.decoyPool.filter((d) => fixtureQuoteIds.has(d.quoteId)) }))
      .filter((r) => r.decoyPool.length >= 2);
    const fixture =
      header +
      genresSql(genres) +
      moviesSql(fixtureMovies) +
      movieGenresSql(fixtureMovies) +
      quotesSql(fixtureQuotes) +
      roundsSql(fixtureRounds);
    await mkdir(FIXTURES_DIR, { recursive: true });
    await writeFile(resolve(FIXTURES_DIR, 'seed.sql'), fixture, 'utf8');
    log.info(
      `wrote fixture: ${fixtureMovies.length} movies, ${fixtureQuotes.length} quotes, ${fixtureRounds.length} rounds`,
    );
  }

  log.info(
    `load complete: ${usedMovies.length} movies, ${quotes.length} quotes, ${pool.length} rounds`,
  );
  log.info('apply locally: from apps/api run "pnpm db:reset" then "pnpm db:seed"');
}

load().catch((error) => {
  log.warn(String(error));
  process.exit(1);
});
